services:
 asterisk-server:
  init: true
  ports:
    - "5060:5060/udp"
    - "5060:5060/tcp"
    - "10000-10099:10000-10099/udp"
    - "8088:8088"
    - "8089:8089"
  volumes:
    - aster-msm:/var/conf/msmtprc
    - aster-spool:/var/spool/asterisk
  networks:
    backend:
